spring:
  application:
    name: reconflow
  datasource:
    url: jdbc:postgresql://localhost:5432/reconflow
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true