spring:
  application:
    name: reconflow
  datasource:
    url: jdbc:postgresql://localhost:5432/reconflow
    username: postgres
    password: root

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: reconflow-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true